### ISSUE TITLE
Add method to Gitlab that allows forcing MR approval

### ISSUE THREAD

**Issue by kubukoz** [pitgull/pitgull#120]
The current way to do this seems to be https://docs.gitlab.com/ee/api/merge_request_approvals.html#delete-merge-request-level-rule - it requires having the ID of the approval rule, and we can get these for a MR by using https://docs.gitlab.com/ee/api/merge_request_approvals.html#get-configuration-1.

If there are any project-wide rules, I think we can't really do anything to remove them from an individual MR. <- needs verification

As a temporary solution, we can use
Use https://docs.gitlab.com/ee/api/merge_request_approvals.html#change-configuration and just set the required approvals to 0.

**Comment by majk-p** [comment]
I'm on it
