### ISSUE TITLE
Add AnyOf, Not nodes in dhall config

### ISSUE THREAD

**Issue by kubukoz** [pitgull/pitgull#128]
Currently, we allow merging matchers with AllOf, which requires all of the matches to pass in order for a rule to be applied - similarly, we should have an AnyOf matcher that only requires one valid match. This should be added in both the dhall files, the JSON config classes in pitgull, and the matcher compiler.

Also, we should have a node that inverts any conditions passed.

**Comment by kubukoz** [comment]
Update: OneOf is now on main, so we're now only missing Not.

**Comment by pkowalcze** [comment]
I'll give it a go

**Comment by kubukoz** [comment]
Closed in #199

**Comment by kubukoz** [comment]
after lots of tears of joy
